 "language": "cpp",
  "compiler": "clang",
  "env": "PARAM_THREADS=\"--enable-threads --with-working-c-locale\" CXXFLAGS=\"\" SWIG_FLAGS=\"\",
  "before_install": [
    "wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -",
    "sudo add-apt-repository --yes 'deb http://ppa.launchpad.net/canonical-x/x-staging/ubuntu precise main'",
    "sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test",
    "if [ ! -z \"$QT\" ] ; then sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa ; fi",
    "sudo apt-get update -qq",
    "sudo apt-get install -q gcc-4.8 g++-4.8 libstdc++-4.8-dev llvm-3.4 clang-3.4 swig python",
    "if [ ! -z \"$QT\" ] ; then sudo apt-get install -q $QT ; fi",
    "sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8",
    "sudo update-alternatives --config gcc"
  ],
  "before_script": [
    "sh ./scripts/fix-timestamps.sh",
    "mkdir objdir",
    "cd objdir"
  ]
